### ISSUE TITLE
Getting this error on login script - screen matches but stops, allows a click through but then app has strange change in next screen

### ISSUE THREAD

**Issue by pputre** [zacfilan/brimstone-recorder#248]
TypeError: Cannot read properties of undefined (reading 'png')
    at TestAction.calculatePixelDiff (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/test.js:1292:31)
    at Player.verifyScreenshot (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/player.js:914:16)
    at async Player.play (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/player.js:380:9)
    at async _playSomething (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/ui/workspace.js:1761:25)
    at async Workspace.playSomething (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/ui/workspace.js:774:5)
    at async Workspace.callMethodByUser (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/ui/workspace.js:187:12)

**Comment by zacfilan** [comment]
I need more info.
1. Turn on the developer mode option
![devmode](https://user-images.githubusercontent.com/4932744/200034938-257da0d1-5b3c-4287-bb4f-4dc8a226c216.png)
2. repro the bug.
3. open devtools ON THE BRIMSTONE WINDOW.
Click the brimstone workspace window.
<ctrl>-<shift>-I
4. open console part of devtools, and set the verbosity to "All levels". Should see a bunch of blue.
![verboseconsole](https://user-images.githubusercontent.com/4932744/200037253-3d5386f1-acb2-498e-b258-1e02a0594819.png)
5. right click the console and click save ass to save the output in a file.
6. attach that file to this issue.

**Comment by zacfilan** [comment]
put a fix in. look out for submitted v1.25.2 to drop early next week.

**Comment by pputre** [comment]
I'll test when I get the drop - Thanks!

**Comment by pputre** [comment]
Closing - fixed in 1.25.4
