### ISSUE TITLE
cannot set desired viewport

### ISSUE THREAD

**Issue by patchworksapp** [zacfilan/brimstone-recorder#66]
Error: cannot set desired viewport
    at Tab.resizeViewport (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/tab.js:86:19)
    at async Player.attachDebugger (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/playerclass.js:503:9)
    at async attachDebuggerToActiveTab (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/ui/workspace.js:291:5)
    at async HTMLButtonElement. (chrome-extension://kjelahkpdbdmajbknafeighkihkcjacd/ui/workspace.js:310:30)

No context really, perhaps new tabs were opened by the user in the middle of the session?

**Comment by patchworksapp** [comment]
![image](https://user-images.githubusercontent.com/89155920/132731154-c82c26f4-53ed-41a7-aeee-c238c74f60dc.png)
